### ISSUE TITLE
Create Stickers with logo

### ISSUE THREAD

**Issue by mbuchoff** [snohio/devopsorlando#13]
- [x] Get a logo ([dark-blue](https://user-images.githubusercontent.com/24615387/265276617-986054b6-8b8a-40e0-99a9-2967a73e6752.png]), [white](https://user-images.githubusercontent.com/24615387/265276627-5157154f-0420-4ec8-a24c-a991537a032b.png))
- [x] Choose a provider ([Sticker mule](https://www.stickermule.com/products/die-cut-stickers))
- [x] Order sample stickers ([Order Confirmation](https://u21395112.ct.sendgrid.net/ls/click?upn=fMAOVhxSGVewlBleKzY4UsGzey7QOBI7x6rsuf7blTDAYS168IRlSRyrxDWx13lZOS1kR7tfhxxk9ptjizRdpeeKicc2i-2FZuaD-2FvZw3Ym64-3DbADY_xaMtViPxIGQwRoYTZ4ao3CIGoCSqPsIndi-2BxmH1JeDhaXhImqY9HAxC-2BKgAFkfpCzjUwlD09lRt2t9d55le4ayEZMv9Jv3sknPZpuLEXnjiLlUo7ggli1025nqruBTpAthOYNBcYxngl3u22aMsOTP9jOGooEeybqoWrAh-2FpwyZ5xp5v4konmD90PXqp1ocDOunJK5JpXD8088OY2pxquU49J5Hf-2FQXIo8qFkllSBcxgQ2i635dp4m8Q8yJSf3k7CwvziMuH0FWCvCAH9hPEsHAs3Ivdt59Gw818Akmp6K6L8bIz6mZ-2F8uU6aFiQ64CgV3GE359HKt5bwEoiw0d5uTdqrm2-2BUafLxMaMkDOxpwiQOfBQCloVOZXDYvIUzKZCLPXru0js8L8x4laOdUU35-2BvmXJ4dcktOs-2FEBzgvhhP3J4gSAKOAizETd8-2FGqgmQXXjP8z79FKPl1h0s42M1LY5Yc4A6UC1OU18OyjUMV-2BWQSCs4-2FjKPrmcKZLoWLOsR2))
- [x] Get sample stickers approved by Orlando DevOps admins
- [x] Order 300 stickers ([Order Confirmation](https://www.stickermule.com/orders/R062351460?token=75ed005ec890ada3), [Proof](https://www.stickermule.com/artworks/14371893/shared?token=54ba325edc5e1ffe8b8f5528fc00f7e4))
- [x] Receive stickers

Consider:
* cost
* quality
* due date
* do we want other swag (too early IMO)

Known options:
* Champions Graphics. Mike Butler knows Ted personally - [Ted Wahl II](https://www.linkedin.com/in/ted-wahl-ii-680294b)
  * No active website!
* [Sticker mule](https://www.stickermule.com/products/die-cut-stickers)
  * $185 for 2x3" for 500. $137 for 300.
  * $9 for 10 sample stickers
 * [VistaPrint](https://www.vistaprint.com/labels-stickers/custom-stickers/die-cut-sticker-singles) doesn't have our exact desired size. $261 for 300
 * [UPrinting](https://www.uprinting.com/die-cut-stickers.html)
   * $225.93 for 250 2x3 (glossy and matte are same price)
   * $236.45 for 500 of the same stickers
* [CustomStickers.com](https://customstickers.com/products/custom-stickers?variant=40410175635643)
  * Only one dimension is specified. Unclear if it is the longest dimension (w x h) or the diagonal length, even after uploading our image
  * $95.99 for 250, $149.99 for 500
  * Matte and gloss are same price

**Comment by mbuchoff** [comment]
Somehow I ended up with a Chef sticker that is more or less what I had pictured, as far as the size, border, custom cutout, and material (matte).
![PXL_20230906_125343308](https://github.com/snohio/devopsorlando/assets/13501758/377b5dab-1344-4421-ab2c-c7a657bec091)

![PXL_20230906_125159026](https://github.com/snohio/devopsorlando/assets/13501758/4de5f87b-c2d5-4aa3-853f-3a413af5588b)

![PXL_20230906_125210588](https://github.com/snohio/devopsorlando/assets/13501758/5d9047f6-d243-40c7-9df9-d0351a88fe1b)

![PXL_20230906_125303984](https://github.com/snohio/devopsorlando/assets/13501758/9858d85b-3f38-49a7-a23d-c5e8df3589c0)

**Comment by snohio** [comment]
![20230906_165421.jpg](https://github.com/snohio/devopsorlando/assets/24615387/aa931fcc-28d0-414a-8390-3a57107c4138)

Sorry for the rotation but since more escapes.  I still think 2x3 ish. The devopsdays tampa is 3 x 4. I like the smaller ones because i can fit more on my laptop.  But with a much detail as we have on the logo any smaller it'll get blurry.

**Comment by snohio** [comment]
My guess is [Printfection](https://www.printfection.com/). That is where all of our swag comes from.

**Comment by snohio** [comment]
Here are the files for the decals. I'm not sure how they will die-cut these but mostly probably just rounding the corners much like the Chef one above..

## PNG

![decal-23.png](https://github.com/snohio/devopsorlando/assets/24615387/64986411-f730-40ba-bab9-b1e6654ee0d8)

## JPG

![decal-23.jpg](https://github.com/snohio/devopsorlando/assets/24615387/c1a0566a-6c6e-4997-bc21-9dea48eb3682)

## Let's do this

I say we just use Stickermule and get it done! I'd probably start with 300, but we can talk about that. And we'll have to figure out the money thing. 😸

**Comment by mbuchoff** [comment]
Just ordered 10 sample stickers from StickerMule. Should be in by 9/22.

**Comment by mbuchoff** [comment]
10 stickers came in!

![Image](https://github.com/snohio/devopsorlando/assets/13501758/bab6a90d-9cd9-410c-ac13-8f436caed08e)

**Comment by snohio** [comment]
I think those turned out amazing! Do you think the size is right? Should we just order a few hundred now? Wait to get feedback from Thursday??

**Comment by mbuchoff** [comment]
I think the size is perfect. I'd feel better getting a second opinion, so I'll show them to Dan on Thursday and see what he thinks.

![PXL_20230918_123941039](https://github.com/snohio/devopsorlando/assets/13501758/196cc970-de52-41cd-97f3-b59c883aa3df)

![PXL_20230918_123959934](https://github.com/snohio/devopsorlando/assets/13501758/4b9de128-a9f2-42ec-b1d9-d504241dbc82)

**Comment by snohio** [comment]
Yep. I think that is perfect. I'll be there Thursday as well. I'm not sure if I am going down on Wednesday or not. I might just to get a space at WeWork and focus on my presentations for next week.

**Comment by mbuchoff** [comment]
Awesome, see you there. Btw, you fondly mention We work a lot. I'm guessing it's hard to focus where you live.

**Comment by snohio** [comment]
I just want to be out of my house! I finished designing and now 3d printing a part for the boys robots. That's the "hard to focus" stuff.

**Comment by mbuchoff** [comment]
![PXL_20230930_163918210](https://github.com/snohio/devopsorlando/assets/13501758/4cfc977b-0761-4388-a4fb-f37044bc4f47)

@snohio, @RecoveringChef, our stickers have arrived!

**Comment by snohio** [comment]
Awesome! Thanks so much.  First stack of hopefully many!
