### ISSUE TITLE
Meetup event - Learn Git (possibly separate from https://www.meetup.com/orlando-devops/events/296295949/)

### ISSUE THREAD

**Issue by mbuchoff** [snohio/devopsorlando#14]
# Meetup event - Learn Git

## User Story

As an event organizer of Orlando DevOps group, I would like to create an event to help people learn Git that are struggling with it so that they can better understand the automation side of DevOps. I don't think there's nearly as much a need to go over GitHub specifically.

## Tasks
- [ ] Decide a date
- [ ] Decide a venue
- [ ] List of things to go over
- [ ] Resubscribe to Zoom for screen sharing

## Cool DevOps things you can do with Git
- Work in parallel with other people and not step on each other's toes
- CI/CD, of course
- Pull requests
- Merge one baseline into another with pipelines
- Automerge master into all branches

## Things to focus on
- Visualizing the history, second most important way to know what's going on (first being the branches)
  - You want a history _graph_. GitHub Desktop only shows linear history, VSCode (by default) shows no history
  - git log --graph --oneline
  - VSCode extension, such as GGP (search extensions for _LinJUn.git-graph-pro_)
  - [Fork](https://git-fork.com/)
- BYOBugs - Encourage attendees to screenshare with their own Git issues for their own personal projects.
- Difference between local and remote, especially if there are multiple people
- What is headless?
- Go through a few under-the-hood details; mainly what's in that .git folder
- Corner-cases to better understand the big picture
  - What if you push to a branch that someone else has already pushed to?
  - What if you move a branch while someone else is using it?
  - TODO: Be prepared to demo rebase, but don't expect things to get that advanced.
  - What is origin/HEAD?
  - Difference between checking out the same commit as a branch and the actual branch

**Comment by snohio** [comment]
"I know Github! Ask me Anything!"

@snohio thoughts on what this should be.
30 minute presentation. 10 minutes on David. 10 minutes on what Xpirit does. 10 - 20 minutes on Github basics and then WTF do you want to know.

**Comment by dsanchezcr** [comment]
Hey team! Thanks again for considering me for this event.

What do you think about the title? 

Title: "GitHub from Zero to Hero"
Description: In this session, we will cover a comprehensive journey through the world of GitHub, a leading platform for software development collaboration and version control. Whether you're an absolute beginner or looking to sharpen your existing skills, this session offers insights and demos to elevate your GitHub skills.

**Comment by mbuchoff** [comment]
@dsanchezcr, that sounds great to me. I just updated the [Meetup event](https://www.meetup.com/orlando-devops/events/296295949) and set you as the host, so feel free to make any further updates you need. Around 9ish, I'll message the ODev's team to update the [EventBrite page](https://www.eventbrite.com/e/devops-igniting-the-potential-of-github-and-github-actions-tickets-728869216447) (we don't have editing privileges to that page).

Also, when I wrote the the notes here, before the DevOps Days event, it was aimed at new developers who were pretty much using Git as a DropBox. If your presentation/demo is completely different, that's fine (ie Git _Hub_ and the _Actions_ side of things). The ideas on this page can be archived for a future event. On the other hand, if you have writer's block, feel free to use anything here.

**Comment by dsanchezcr** [comment]
Perfect! Thanks, and that's fine! I can cover the basics of Git and GitHub as part of the presentation!

**Comment by mbuchoff** [comment]
@dsanchezcr, this issue might be causing some confusion. My current understanding is that you are giving the entire presentation (again, feel free to use as many or few ideas on this page as you want). If your understanding is that I am giving some of it, just let me know with enough time to prepare.

**Comment by dsanchezcr** [comment]
Sorry for the confusion that was my expectation as well. I am ok doing an AMA as part of the session. The structure looks good to me. Thanks!

**Comment by mbuchoff** [comment]
@dsanchezcr, great talk last night. I especially found the questions and tangents interesting (ie using a GitHub action to build/push to GitHub pages) Thanks for giving it, and I hope your talk at ONETUG also goes well.

Closing this issue. Will look at it again in 6 months to see if we want to do something like this again for the group.
