### ISSUE TITLE
Build a map from the survey

### ISSUE THREAD

**Issue by mbuchoff** [snohio/devopsorlando#18]
## User Story

As a co-organizer of Orlando DevOps group, I would like to build a map so that we know where people are coming from. @snohio mentioned there was a tool out there to easily do this.

## Tasks

- [X] Find a Tool *[Mapline](https://app.mapline.com/map/map_383308ec)*
- [X] Enter Data from the first 22 people.
- [X] Paste results
- [ ] Continue entering

## Extra Notes

> It's not obvious from our results where most people are coming from, so we don't know where the ideal locations are.

**Comment by snohio** [comment]
I'll try to wrack my brain on this one. I used it in the early 00's to map out all of the locations that I supported servers on. It's a very vague memory. 😼

**Comment by snohio** [comment]
That wasn't the tool. but I think it works for our needs.

**Comment by snohio** [comment]
@mbuchoff How does this look?

**Comment by mbuchoff** [comment]
Perfect!
