### ISSUE TITLE
Create a Survey for the DevOps Members

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#2]
# Create a Survey for the DevOps Members

## User Story

As a leader of the Devops Orlando organizing team, I would like to create and send a Survey to all old members of DevOps Orlando Meetup members and the ODevs members so that we know what topics people want to hear about and days that work the best for them.

## Useful Information

[Edit the Survey Here](https://docs.google.com/forms/d/1fxfryb8sQAYBP86qinS1jTkErEUCvEsVK3I0d7-ScLA/edit?usp=drive_web)

**Comment by snohio** [comment]
Please feel free to add what questions we should ask the folks this gets sent to..

* Interested in DevOps
  * Yes or No
* Dev or Op or Sec?
   * Each one of those is an option
* Level of Odoption / Experience ( 1 - 5)
* Where are you located (Open Text Box)
* Best days and times times 
  * Each day is a selection with Moring, Afternoon, Evening.
* Favorite Location (Open Text Box)
* Topic Suggestions (Open Text Box)
* What Socials do you use?
  * Checkboxes for X (Twitter), Instagram, LinkedIn, Threads, Facebook, Mastodon, Blue Sky, Other
* Are you interested in assisting / volunteering with events and other things we need to do?
* Email address to Join our Mailing List (Open Text Box - Validate @ . something.)

I would assume that we would just do a SUrvey Monkey or we could do a Google Form.

**Comment by mbuchoff** [comment]
Looks pretty complete. Maybe we could split Topic Suggestions into:
- DevOps topics you are familiar with
- DevOps topics you are curious about
- Types of events you would like
  - Hands-on
  - Demonstration (ie screenshare while using a tool)
  - Presentation (ie boring noninteractive PowerPoint slides)

**Comment by mbuchoff** [comment]
I think I'm done. Can someone could review this and make sure it's concise and complete?

**Comment by snohio** [comment]
@mbuchoff - Nice job! I made some tweaks and added just a thing or two here or there. Look at the results and if good, let's :shipit: .

**Comment by mbuchoff** [comment]
@snohio, can we either remove _Favorite Event Types_ or put it after _Topic Suggestions for Events_? I want to avoid leading the witness when asking for ideas.

**Comment by snohio** [comment]
@mbuchoff - I made the change to what I suggested above. I do think we're right though. I am curious about topics people want to see. 

I also made some changes to how some of the questions were asked and asked about how folks (like to) get notified of events. I want to understand how best to communicate with our community!

**Comment by mbuchoff** [comment]
@snohio, looks good! 🚢

**Comment by mbuchoff** [comment]
@snohio, @RecoveringChef, any objections with me sending this out? I'm guessing meetup and #orlando-devops-meetup Slack channel.

**Comment by snohio** [comment]
Sounds great! And the LinkedIn group. Let me know if you need help writing the correspondence that goes with it.

**Comment by mbuchoff** [comment]
@snohio, @remotesynth, how's this sound?

> Hi, everyone. In the past few months, Mike (the other Mike), Dan, and I have gotten serious about getting this group up and running again and want to know what you want it be like. We've attached a survey, but if you have thoughts that aren't specifically asked, we want to hear them (and there's a spot for that). Also, all questions are optional, so feel free to leave out any personal information and if you simply get tired of answering questions, just "next" your way through it.
> 
> https://forms.gle/HCHMf4KukhzpjsrY7
> 
> Thanks and looking forward to meeting you (or seeing you again) at a future event.

**Comment by mbuchoff** [comment]
@snohio, can I move this to _done_?
