### ISSUE TITLE
Host lean Coffee at DevFest CFL

### ISSUE THREAD

**Issue by RecoveringChef** [snohio/devopsorlando#21]
For Table: get stickers, make sign 
For Event:  coffee,, accoutrements

**Comment by RecoveringChef** [comment]
A great time was had by all. Maybe 12-15 people came. Good discussions with a mix of students and devop curious and some working devops.  Jacob Hiers was GREAT co-hosting and explaining the format and keeping topics moving.

Got 4 joins to the LinkedIn group and 3 to the meetup group. Had stickers and sign at sign-in table and saw several on laptops at event.

**Comment by snohio** [comment]
Thanks for participating! I appreciate all of the reposting Javi did as well!
