### ISSUE TITLE
Event - Terraform/Tofu workshop

### ISSUE THREAD

**Issue by mbuchoff** [snohio/devopsorlando#33]
Don't forget drift detection
[Event on meetup](https://www.meetup.com/orlando-devops/events/299226778)
[Example project with tofu](https://github.com/mbuchoff/devops-vanilla-example/tree/main)

**Comment by snohio** [comment]
I did create that template that will have all of the common tasks on it.

**Comment by mdaverde** [comment]
@mbuchoff 

Did you mean to create under the Millenials of Orlando?

**Comment by mbuchoff** [comment]
@mdaverde , thank you for seeing that. Might explain why no one signed up.

**Comment by mbuchoff** [comment]
> I did create that issue template that will have all of the common tasks on it.

@snohio, sorry for missing that. Can you point me to the template? From https://github.com/snohio/devopsorlando/issues/24, I had thought the template was still under construction.

**Comment by snohio** [comment]
If you click on New Issue in the devopsorlando github repo, it should give you this screen:
![image](https://github.com/snohio/devopsorlando/assets/24615387/d55090fb-6f59-4bdf-b125-eba86e70e998)
Click the Event Meetup Template.
Or directly here: https://github.com/snohio/devopsorlando/issues/new?assignees=&labels=Meetup+Event&projects=&template=meetup.md&title=MONTH%2C+DAY%2C+YEAR+-+Meetup+Event+TYPE

**Comment by mbuchoff** [comment]
Closing as a duplicate of https://github.com/snohio/devopsorlando/issues/34
