### ISSUE TITLE
Organize September Lean Coffee / Beer Event in Lake Mary area

### ISSUE THREAD

**Issue by snohio** [snohio/devopsorlando#4]
As an organizer of Orlando DevOps Meetup, I would like to have organized, scheduled, and posted the Meetup Event on (or about) September 19th at 7pm in Lake Mary so that we can start to move the monthly lean coffee / beer events around and attract new people.

**Comment by mbuchoff** [comment]
I'll be driving around the Lake Mary area this weekend to look for a good venue.

**Comment by mbuchoff** [comment]
I spent a good amount of the afternoon today at 4th Street Bar and Grill, liked it, and put reservations in for our group.

@snohio, when I created the event, you were added as a _yes_ by default and Meetup won't let me switch you to _unreplied_, so of course you're welcome, but if something important comes up, no worries.

**Comment by snohio** [comment]
We still need to close these issues (for now) as I don't have automation configured to close the issues once they have been set to Done.

Also, let's not close this one until it is officially published.

**Comment by mbuchoff** [comment]
Here's the page: https://www.meetup.com/orlando-devops/events/294924823/

By _published_, do you mean _announced_? If so, I usually wait until a month out to announce events. Good idea here?

**Comment by snohio** [comment]
Yes, announced. Just leave this open until it is announced so we have another reminder.  Yeah. a month before on Lean Coffee's might be good. Maybe 45 days for the monthly bigger meetups, especially the hackathons. Folks might want to prepare for that a bit more. 
Thanks!

**Comment by snohio** [comment]
Ok. Let's close when we promote. :) Need to get our #9 done.

**Comment by snohio** [comment]
## We need to move the date

Well, as discussed, I suck at dates. I know we chatted about this on Slack, but for here, we need to move the date.

September 21st is DevOpsDays Tampa. I am going to be chatting with the organizers on Monday. They are going to give all of our folks that go 50% off (which isn't really anything they aren't doing for their own group) and asked if we wanted to sponsor (which I don't know what that means - if he meant Orlando DevOps or Chef and if ODO, do community groups pay? It does look like they are having issues getting sponsors which is a little scary. But that's a whole another topic. 

Ok. My laptop battery is about dead so, options:

### Options 

Monday the 18th (I can do that) Tuesday the 19th (I probably can't make that), Saturday the 23rd.

Tuesdays are the evening that I am unavailable. I didn't know what day it would be last time.

**Comment by mbuchoff** [comment]
@snohio 
I sense you typed this in a hurry, so want to confirm that Saturday, the 23rd at lunchtime is still good.

Any suggestions for places? If not, I'll swing by the restaurant this weekend (their food is pretty good) and make sure it's not too loud on a Saturday.

**Comment by mbuchoff** [comment]
All set. Moved to the 27th (Wed). Mondays and Tuesdays they have bingo and trivia (loud) and Saturdays are crowded, at least during lunch.

**Comment by snohio** [comment]
Sounds good. Thanks! I will be in Seattle for this one at ChefConf - but you all have fun!

**Comment by mbuchoff** [comment]
@snohio, @RecoveringChef, can we mark this as Done?

https://www.meetup.com/orlando-devops/events/294924823/

**Comment by snohio** [comment]
I like to wait until afterwards with survey results and debrief. One of these days I'll make that Meetup template that has a prepopulated task list.

**Comment by RecoveringChef** [comment]
To me if the story card is to "organize event" then the after action parts are a separate card/ticket. Unless we just want to make 1 big ticket for "host X event" and all agree it is for planning, executing, after actions. 
I am flexible and that might be me just reading too much into the card title.
We just need to organize and find our norms

**Comment by snohio** [comment]
I would prefer bigger cards (I guess more of a feature) but either way works.. We can also create a swim lane for Review that has the follow up actions to be taken care of then.

I can make templates for both Events and Followups. @mbuchoff thoughts? Two cards/issues per event or one?

**Comment by mbuchoff** [comment]
I think one big card makes sense. Otherwise, if it's two small cards and important information in each card, we'd want to link them; not worth the effort.

A swimlane for review also makes sense. Once and a while, we will be getting together to discuss a plethora of issues/tasks (this coming Monday, I presume), so that would be a convenient place to list everything.

**Comment by snohio** [comment]
Awesome job! 2.5 new people.
